[package]
name = "backup"
version = "0.1.0"
authors = ["Alice Ryhl <alice@ryhl.io>"]

[dependencies]
backblaze-b2 = "0.1.4"
hyper = "^0.10.10"
hyper-native-tls = "^0.2.2"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
rand = "^0.3"
sha1 = "^0.2.0"
